### ISSUE TITLE
Provide nuget package?

### ISSUE THREAD

**Issue by ebraminio** [blinkseb/harfbuzz#2]
Hi. Thank you for this. Is it possible to provide a [native nuget package](http://blogs.msdn.com/b/vcblog/archive/2013/06/18/deep-dive-into-nuget-native-part-one.aspx)? freetype already has a native nuget package.

**Comment by ebraminio** [comment]
I can add it on nuget and pull request nuspec by myself if you are not interested in but a little help on which headers are needed would be nice.

**Comment by behdad** [comment]
Please go ahead!  I never heard of nuget before.

**Comment by ebraminio** [comment]
Here is [my nuspec](http://pastebin.com/WCBQURLD) but I confess making the .targets wasn't just easy that I thought. This [sample](https://github.com/coapp-packages/freetype/tree/master/COPKG) which is using [CoApp](http://coapp.org/tutorials/building-a-package.html) is just very complicated as need of various static libs for different visual studio versions which I don't own and most worst part for me is [CoApp installer](http://downloads.coapp.org/files/CoApp.Tools.Powershell.msi) just isn't working on my machine. I hope @madewokherd could make this at least as a part of [coapp-packages](https://github.com/coapp-packages) as freetype and SDL already has nuget package and making one for HarfBuzz would make building [this](https://github.com/lxnt/ex-sdl-freetype-harfbuzz) for Windows users easy.
